// Archivo nuevo — centraliza datos de México usados en múltiples componentes

export const ESTADOS_MEXICO = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Estado de México",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];

export const MUNICIPIOS_NL = [
  "Monterrey",
  "San Nicolás de los Garza",
  "Guadalupe",
  "Apodaca",
  "San Pedro Garza García",
  "General Escobedo",
  "Santa Catarina",
  "Juárez",
  "García",
  "Linares",
  "Otro",
];
